import '../App.css';

function WhatsOffered (){

  return( 
    <div>  <div className='boxTwo' style={{  marginLeft: '5%', marginTop: '5%'}}> Bouldering: is a type of climbing that is done without a rope or harness, typically on shorter, lower-altitude rock formations or indoor walls that are designed for bouldering. Bouldering routes, also known as "problems," are typically shorter and more intense than other types of climbing routes, with a focus on technical movement and problem-solving. Bouldering is a great way to build strength, technique, and confidence, and is often seen as a gateway into the world of climbing.</div>
    <div className='boxTwo' style={{ alignSelf:'flex-end', marginRight: '40%', marginTop: '5%'}} >Top Rope Climbing: a type of climbing that is done with a rope that is anchored at the top of a climbing route and threaded through a rope-holding device known as a belay device. The climber wears a harness that is attached to one end of the rope, while a belayer manages the other end of the rope from the ground. As the climber ascends the route, the rope is kept taut by the belayer, providing a safety net in case of a fall. Top rope climbing is often seen as a beginner-friendly form of climbing, as it allows climbers to focus on technique and movement without the added stress of managing a rope system.</div>
    <div className='boxTwo' style={{  marginLeft: '5%', marginTop: '6%'}}>Lead Climbing: Lead climbing is a more advanced form of climbing that involves the climber clipping their rope into anchors as they ascend the route. In lead climbing, the rope is not already in place, as it is in top rope climbing. Instead, the climber carries the rope with them as they climb, clipping it into pre-placed bolts or gear as they go. The lead climber is also responsible for managing their own rope system, which adds an additional layer of complexity and risk to the climb. Lead climbing is a popular form of climbing for those who are looking for a greater challenge and are comfortable with managing a more complex rope system.</div>
    <div className='boxTwo' style={{  marginLeft: '5%',  marginTop: '3%'}}>Speed Climbing: Speed climbing is a form of climbing that involves racing up a pre-set route as quickly as possible. Speed climbing is typically done on artificial climbing walls, and routes are designed with speed in mind, featuring minimal holds and a steep incline. Speed climbing has become increasingly popular in recent years, especially since it was added as an Olympic event in 2021. Speed climbers often train specifically for this type of climbing, focusing on explosive power and technique to shave fractions of a second off their time.</div>
    <div className='boxTwo' style={{  marginLeft: '5%',  marginTop: '3%'}}>Slacklining: Slacklining is a sport that involves balancing on a narrow piece of webbing, usually between two anchor points like trees or posts. The webbing is typically flat and only a few centimeters wide, requiring the slackliner to use their core strength and balance to stay upright. Slacklining can be done at different heights and lengths, ranging from a few inches off the ground to several hundred feet above the ground. Slacklining can be practiced as a solo activity or as a group activity, and is often seen as a meditative and peaceful way to improve balance, focus, and mindfulness. In recent years, slacklining has also become a competitive sport, with athletes competing in a variety of disciplines, such as longlining, highlining, and tricklining.</div>
    <div className='boxTwo' style={{ alignSelf:'flex-end', marginRight: '45%', marginTop: '8%'}}>Parkour: Parkour is a discipline that involves navigating obstacles in the environment, such as walls, railings, and other urban structures, in a fluid and efficient way. Practitioners of parkour, also known as "traceurs," use a variety of movements and techniques, such as running, jumping, climbing, and vaulting, to move through their environment in creative and often acrobatic ways. Parkour is typically practiced in urban environments, but it can also be practiced in natural environments like forests or mountains. Parkour is often seen as a form of self-expression, physical training, and personal challenge, and can be practiced alone or in groups.</div>
    <div className='boxTwo' style={{  marginLeft: '5%', marginTop: '6%'}}>In cheerleading, teams of athletes work together to create choreographed routines that include tumbling, jumps, pyramids, and stunts. Cheerleaders use their athleticism, strength, and coordination to perform these elements with precision and flair, often incorporating music and cheers to engage the audience and create a fun and exciting atmosphere.</div>
    </div>
  )
};

export default WhatsOffered;